apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: wisecow=saijathin/wisecow
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/wisecow.update-strategy: newest-build
    name: wisecow-updater
    namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/saijathin51/wisecow-submission
    path: kubernetes/manifests           
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true